<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>anycpu</PlatformTarget>
		<LangVersion>latest</LangVersion>
		<OutputType>Library</OutputType>
		<AssemblyTitle>Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations</AssemblyTitle>
		<Product>Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations</Product>
		<AssemblyName>Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations</AssemblyName>
		<RootNamespace>Skyline.DataMiner.Solutions.PeopleAndOrganizations</RootNamespace>

		<PackageId>Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations</PackageId>
		<PackageTags>Skyline;DataMiner</PackageTags>
		<PackageProjectUrl>https://skyline.be</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageIcon>Icon.png</PackageIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<Authors>SkylineCommunications</Authors>
		<Company>Skyline Communications</Company>
		<Description>Provides an internal API for People and Organizations.</Description>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/SkylineCommunications/Skyline.DataMiner.Solutions.PeopleAndOrganizations</RepositoryUrl>
		<Deterministic>false</Deterministic>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations.Tests" />
		<InternalsVisibleTo Include="Skyline.DataMiner.Dev.Utils.Solutions.PeopleAndOrganizations.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="nuget\Icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Skyline.DataMiner.ConnectorAPI.SkylineLockManager" Version="1.3.4" />
		<PackageReference Include="Skyline.DataMiner.Dev.Common" Version="10.5.11.1" />
		<PackageReference Include="Skyline.DataMiner.Dev.Utils.SDM.Abstractions" Version="1.0.1" />
		<PackageReference Include="Skyline.DataMiner.Dev.Utils.Solutions.MediaOps.Plan" Version="1.6.0-alpha008" />
		<PackageReference Include="Skyline.DataMiner.Utils.DOM" Version="10.5.2.5" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" Version="2.2.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
